server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #uri: file:///F:\java\GitApp\SpringCloudMsa1\ConfigRepository
          uri: https://github.com/ytw9699/ConfigRepository
#         username:
#         password:
